export enum HTTP_STATUS {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  PAYLOAD_TOO_LARGE = 413,
  UNPROCESSABLE_ENTITY = 422,
  FAILED_DEPENDENCY = 424,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

// Error Codes
export enum SERVER_ERROR {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export enum AUTH_ERROR {
  USER_KEY_MISSING = 'USER_KEY_MISSING',
  USER_KEY_INVALID = 'USER_KEY_INVALID',
}

export enum CLIPBOARD_ERROR {
  CLIPBOARD_NOT_FOUND = 'CLIPBOARD_NOT_FOUND',
}
